version: '3.7'
services:
  db:
    image: mysql:8
    ports:
      - "3309:3309"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld # maps the file that contains socket information that enables the web service to talk to the database service
      - ./db:/var/lib/mysql # creates a local db folder where database information is saved if the service db is destroyed
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      db:
        condition: service_healthy
