name: email sender test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: updated coverage badge
      CI_COMMIT_AUTHOR: Continuous Integration

    services:
      mysql:
        image: mysql:8.1
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports: ['3306:3306']
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install genbadge[all]
        
    - name: Run Tests
      run: |
        coverage run manage.py test
        coverage xml -o ./reports/coverage/coverage.xml --omit="*/test*"
        genbadge coverage -o ./reports/coverage-badge.svg

      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: ${{ secrets.MYSQL_PORT }}

    - name: Commit to update the badge
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git add .coverage
        git add reports/
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push